### ISSUE TITLE
Port is not working in my local side

### ISSUE THREAD

**Issue by jovanovic-nemanja** [jovanovic-nemanja/CorpSec#1]
It's Laravel backend and vue.js frontend project. So i ran it as port method. But backend is not working well.
So should i run it in htdocs env?

**Comment by fastcod** [comment]
Yes. That was for localhost server method running platform. So you should run it in htdocs when you are running project in windows.
So port method will be not run for you.

**Comment by fastcod** [comment]
I putted the guide in ReadMe.txt.
